version: '3.8'

services:
  db:
    container_name: mysql-opening-day
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'test'
      MYSQL_DATABASE: 'openingDayAppDb'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  app:
    build:
      context: .
      dockerfile: Dockerfile  # Optional if named Dockerfile in the context directory
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: 'development'
      DB_HOST: 'db'  # Refers to the db service
      DB_USER: 'root'
      DB_PASSWORD: 'test'
      DB_NAME: 'openingDayAppDb'
    depends_on:
      - db

volumes:
  db_data:
